name: Update Data
on:
  workflow_dispatch:

jobs:
  update-data:
    name: Update Data
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: main
      - name: Formatter Setup
        uses: actions/checkout@v4
        with:
          repository: windy-civi/windy-civi
          path: windy-civi
      - name: Scrape Data
        working-directory: ./main
        run: |
          docker pull openstates/scrapers:28675b011eef5bb35a758d05d1b7313d515c28ea
          docker run openstates/scrapers:28675b011eef5bb35a758d05d1b7313d515c28ea --help
          mkdir _working
          docker run \
              -v "$(pwd)/_working/_data":/opt/openstates/openstates/_data \
              -v "$(pwd)/_working/_cache":/opt/openstates/openstates/_cache \
              openstates/scrapers:28675b011eef5bb35a758d05d1b7313d515c28ea \
              il bills --scrape --fastmode
          ls -al _working
          du -sh _working
          tree _working

      # - name: Generate Report
      #   working-directory: ./main
      #   run: |
      #     export UPDATE_DATE=$(date)
      #     echo $UPDATE_DATE > report.txt
      #     git config user.email "no_email"
      #     git config user.name "Windy Civi Bot"
      #     git add report.txt
      #     git commit -m"Automated report update (report dated $UPDATE_DATE)"
      #     git push
